package com.taskmanager.mapper;

import com.taskmanager.dto.response.AuthResponse;
import com.taskmanager.model.User;
import org.springframework.stereotype.Component;

/**
 * UserMapper — converts User entities to response DTOs.
 *
 * <p><b>S Principle</b>: Single responsibility — mapping user data.
 * The JWT token is passed in as a parameter since token generation
 * is handled by JwtTokenProvider, not by this class.
 */
@Component
public class UserMapper {

    /**
     * Builds an AuthResponse from a User entity and a pre-generated JWT token.
     *
     * @param user  the saved user entity
     * @param token the JWT token generated by JwtTokenProvider
     * @return the auth response DTO
     */
    public AuthResponse toAuthResponse(User user, String token) {
        return AuthResponse.builder()
                .token(token)
                .username(user.getUsername())
                .email(user.getEmail())
                .userId(user.getId())
                .build();
    }
}
